### ISSUE TITLE
Adding compiling environment specs

### ISSUE THREAD

**Issue by ztzhang** [NVlabs/planercnn#3]
Hi,

I tried to compile the mask-rcnn kernels and it seems it does not work with cuda10.0 and gcc versions higher than 6. Switching to gcc9.0 and cuda9.0 works. 

Would it be possible to add this in the README.MD? Thanks!

**Comment by art-programmer** [comment]
Thank you for the note! Just added.

**Comment by wullish** [comment]
Hi @ztzhang  , I didn't understand what you wrote. You were using GCC version 6 but didn't worked because it does not work with version higher than 6 and then you switched to version 9 and worked? What?! Can you inform yours system specs, please?

I'm trying to use this pytorch repo with AWS Sagemaker p2.xlarge instance (rhel fedora 2018.3 with single GPU K80) which by default has CUDA 10.0 and GCC 4.8.5. So I've installed CUDA 9.0 and as GCC is version 4.8.5 by default (that's not higher than 6) but it didn't worked when trying to compile roialign.

The default configs (CUDA 10.0 and GCC 4.8.5) works with Mask R-CNN backbone using TensorFlow.

What I'm missing here @art-programmer ?

Thanks guys.

**Comment by ztzhang** [comment]
@wullish sorry a typo. I did it with gcc 5.3.0. I never tried older version of gcc, as versions before 5.x may not have c++11 as default. 
Under CUDA 10.0 the error message is gcc version higher than 6 is not supported, which I reported faithfully. I simply meant CUDA 10.0 AND gcc version higher than 6, as a combination, fails.

**Comment by wullish** [comment]
Thanks man. Now, it's much clear! I'm going to try.

**Comment by wullish** [comment]
I'm still getting "cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1" when compiling "python build.py" roialign after updating to 5.3.0 gcc with CUDA 9.0.

I dont know what to do anymore. I've tried with python3.7 and 3.6 but no success. I'm using sm_37 which is the version for K80 according to this guy [here](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/).

Can you share yours envs specs or point to where I'm possibly doing wrong?

Thanks!

**Comment by wullish** [comment]
Solved! Happens that cudatoolkit=9.0 wasn't installed in my environment.

Best.
